; ESP32-C3 Super Mini (4MB flash) port
[platformio]
src_dir = esp32-birdnet-mic

[env:esp32-c3-super-mini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_size = 4MB
board_build.flash_mode = dio
board_build.partitions = default.csv
board_build.f_cpu = 160000000L
monitor_speed = 115200
upload_speed = 921600
upload_port = COM8
board_upload.flash_size = 4MB
board_upload.flash_mode = dio
lib_deps =
    tzapu/WiFiManager@^2.0.17
    knolleary/PubSubClient@^2.8
build_flags =
    -fno-exceptions
    -fno-unwind-tables
    -fno-asynchronous-unwind-tables
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
